// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvwkehbwxeolneugichw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2d2tlaGJ3eGVvbG5ldWdpY2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2OTM3ODUsImV4cCI6MjA4NzI2OTc4NX0.Nf18BCYLuCp5ZBsKO3PQjTczV2jHPmVu0mCsxpLh_EQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});